solar:
  system:
    cronJob: 0 */2 * * *
    daysPeriod: 3600

server:
  servlet:
    context-path: /solar-system

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    username: b9aef16db746b0
    #    username: root
    password: 872a8a60
    #    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/heroku_3bad20f3b063f16?reconnect=true&useSSL=false&useUnicode=yes&characterEncoding=utf8&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/weather_forecast?reconnect=true&useSSL=false&useUnicode=yes&characterEncoding=utf8&serverTimezone=UTC
