solar:
  system:
    cronJob: 0 0/5 * * * *
    daysPeriod: 3600

server:
  servlet:
    context-path: /solar-system

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    username: b9aef16db746b0
    password: 872a8a60
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/heroku_3bad20f3b063f16
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 120000
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
