#spring:
#  cloud:
#    appId: ml-solar-system
#    gcp:
#      sql:
#        instance-connection-name: ml-solar-system-270605:southamerica-east1:ml-solar-system
#        database-name: ml_solar_system
#      logging:
#        enabled: true
#  jpa:
#    hibernate:
#      ddlAuto: update
#    generate-ddl: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    datasource:
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#
#solar:
#  system:
#    cronJob: 0/1 * * * * *
#    daysPeriod: 3600
